import hashlib

import pandas as pd
import pytest

from freight_audit_lab.config import load_config
from freight_audit_lab.generate import generate_reference


@pytest.fixture(scope="module")
def tables(tmp_path_factory):
    return generate_reference(load_config(), tmp_path_factory.mktemp("data"))


def _hashes(ref_dir):
    return {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(ref_dir.glob("*.csv"))}


def test_same_seed_identical_files(tmp_path):
    cfg = load_config()
    generate_reference(cfg, tmp_path / "a")
    generate_reference(cfg, tmp_path / "b")
    a, b = _hashes(tmp_path / "a" / "reference"), _hashes(tmp_path / "b" / "reference")
    assert len(a) == 10
    assert a == b


def test_data_readme_says_synthetic(tmp_path):
    generate_reference(load_config(), tmp_path)
    assert "SYNTHETIC DATA – generated by freight_audit_lab.generate" in (tmp_path / "README.md").read_text()


def test_delivery_after_ship(tables):
    shp = tables["shipments"]
    assert (shp["delivery_date"] > shp["ship_date"]).all()


def test_bols_unique_eight_digits(tables):
    bol = tables["shipments"]["bol"]
    assert bol.is_unique
    assert bol.str.fullmatch(r"\d{8}").all()


def test_rate_rows_never_overlap(tables):
    card = tables["rate_card"].sort_values(["carrier_id", "lane_id", "effective_from"])
    for _, grp in card.groupby(["carrier_id", "lane_id"]):
        starts, ends = grp["effective_from"].tolist(), grp["effective_to"].tolist()
        for prev_end, next_start in zip(ends, starts[1:]):
            assert next_start == prev_end + pd.Timedelta(days=1)


def test_every_shipment_has_a_contract_on_its_ship_date(tables):
    card, shp = tables["rate_card"], tables["shipments"]
    merged = shp.merge(card, on=["carrier_id", "lane_id", "mode"])
    in_force = merged[(merged["effective_from"] <= merged["ship_date"])
                      & (merged["effective_to"] >= merged["ship_date"])]
    assert in_force["shipment_id"].value_counts().eq(1).all()
    assert len(in_force) == len(shp)


def test_authorizations_and_reweighs_are_in_transit_window(tables):
    shp = tables["shipments"].set_index("shipment_id")
    for df, col in ((tables["authorizations"], "authorized_at"),
                    (tables["reweigh_certificates"], "certified_at")):
        j = df.join(shp, on="shipment_id")
        assert ((j[col] >= j["ship_date"]) & (j[col] <= j["delivery_date"])).all()
    rw = tables["reweigh_certificates"].join(shp, on="shipment_id")
    assert (rw["mode"] == "LTL").all()
    assert (rw["certified_weight_lbs"] > rw["weight_lbs"]).all()


def test_reference_files_hide_simulator_settings(tables):
    assert "error_multiplier" not in tables["carriers"].columns
    assert "lag_median_days" not in tables["carriers"].columns
