"""Synthetic data generator. Stage 1 writes the shipper's reference data to data/reference/."""

from pathlib import Path

import numpy as np

from freight_audit_lab.config import REPO_ROOT
from freight_audit_lab.generate import diesel, network, rates, shipments

DATA_README = """# data/

SYNTHETIC DATA – generated by freight_audit_lab.generate

Nothing in this folder describes a real company, carrier, shipment, or person. City names
and coordinates are real public geography; carrier names are invented. Regenerate with
`python -m freight_audit_lab.run` (same config.yaml and seed give byte-identical files).

- `reference/`    what the shipper legitimately knows (lanes, contracts, shipments, ...)
- `public/`       optional EIA weekly diesel CSV supplied by the author
- `ground_truth/` answer key; only evaluate.py and sweep.py may read it
"""


def write_csv(df, path):
    """Write a CSV the same way every time (ISO dates, \\n line endings) so reruns hash equal."""
    df.to_csv(path, index=False, date_format="%Y-%m-%d", lineterminator="\n")


def generate_reference(cfg, data_dir=REPO_ROOT / "data", rng=None):
    """Build all Stage 1 reference tables, write them to data_dir/reference, and return them.

    The random generator is created once from config seed and drawn in a fixed order, so
    the same config always produces the same files.
    """
    rng = rng if rng is not None else np.random.default_rng(cfg["seed"])
    data_dir = Path(data_dir)
    ref_dir = data_dir / "reference"
    ref_dir.mkdir(parents=True, exist_ok=True)
    (data_dir / "README.md").write_text(DATA_README)

    facilities = network.build_facilities(cfg)
    destinations = network.build_destinations(cfg)
    lanes = network.build_lanes(facilities, destinations, cfg, rng)
    carriers = network.build_carriers(cfg)
    carrier_lanes = network.assign_carriers(lanes, cfg, rng)
    rate_card = rates.build_rate_card(carrier_lanes, lanes, cfg, rng)
    diesel_weekly = diesel.build_diesel(cfg, rng)
    fsc_table = rates.build_fsc_ltl_table(diesel_weekly, cfg)
    shp = shipments.build_shipments(lanes, carrier_lanes, facilities, cfg, rng)
    auths = shipments.build_authorizations(shp, cfg, rng)
    reweighs = shipments.build_reweighs(shp, cfg, rng)

    tables = {"facilities": facilities, "destinations": destinations, "lanes": lanes,
              "carriers": carriers, "rate_card": rate_card, "diesel_weekly": diesel_weekly,
              "fsc_ltl_table": fsc_table, "shipments": shp, "authorizations": auths,
              "reweigh_certificates": reweighs}
    for name, df in tables.items():
        write_csv(df, ref_dir / f"{name}.csv")
    return tables
