"""Synthetic data generator.

Stage 1 writes the shipper's reference data to data/reference/. Stage 2 builds canonical
invoices, injects traps and errors, and writes the messy carrier files (data/raw/), the AP
receipt log (data/reference/), and the answer key (data/ground_truth/).
"""

import shutil
from pathlib import Path

import numpy as np

from freight_audit_lab.config import REPO_ROOT
from freight_audit_lab.csv_io import write_csv
from freight_audit_lab.generate import (diesel, ground_truth, inject, invoices, network, rates,
                                        render, shipments, traps)

DATA_README = """# data/

SYNTHETIC DATA – generated by freight_audit_lab.generate

Nothing in this folder describes a real company, carrier, shipment, or person. City names
and coordinates are real public geography; carrier names are invented. Regenerate with
`python -m freight_audit_lab.run` (same config.yaml and seed give byte-identical files).

- `reference/`    what the shipper legitimately knows (lanes, contracts, shipments, AP receipt log, ...)
- `raw/invoices/` messy carrier invoice files, one folder per carrier, one file per month received
- `public/`       optional EIA weekly diesel CSV supplied by the author
- `normalized/`   clean invoice tables produced by normalize.py from `raw/` and `reference/`
- `ground_truth/` answer key; only evaluate.py and sweep.py may read it
"""


def generate_reference(cfg, data_dir=REPO_ROOT / "data", rng=None):
    """Build all Stage 1 reference tables, write them to data_dir/reference, and return them.

    The random generator is created once from config seed and drawn in a fixed order, so
    the same config always produces the same files.
    """
    rng = rng if rng is not None else np.random.default_rng(cfg["seed"])
    data_dir = Path(data_dir)
    ref_dir = data_dir / "reference"
    ref_dir.mkdir(parents=True, exist_ok=True)
    (data_dir / "README.md").write_text(DATA_README)

    facilities = network.build_facilities(cfg)
    destinations = network.build_destinations(cfg)
    lanes = network.build_lanes(facilities, destinations, cfg, rng)
    carriers = network.build_carriers(cfg)
    carrier_lanes = network.assign_carriers(lanes, cfg, rng)
    rate_card = rates.build_rate_card(carrier_lanes, lanes, cfg, rng)
    diesel_weekly = diesel.build_diesel(cfg, rng)
    fsc_table = rates.build_fsc_ltl_table(diesel_weekly, cfg)
    shp = shipments.build_shipments(lanes, carrier_lanes, facilities, cfg, rng)
    auths = shipments.build_authorizations(shp, cfg, rng)
    reweighs = shipments.build_reweighs(shp, cfg, rng)

    tables = {"facilities": facilities, "destinations": destinations, "lanes": lanes,
              "carriers": carriers, "rate_card": rate_card, "diesel_weekly": diesel_weekly,
              "fsc_ltl_table": fsc_table, "shipments": shp, "authorizations": auths,
              "reweigh_certificates": reweighs}
    for name, df in tables.items():
        write_csv(df, ref_dir / f"{name}.csv")
    return tables


def generate_invoices(cfg, tables, data_dir=REPO_ROOT / "data", rng=None):
    """Stage 2: canonical invoices -> traps -> errors -> messy files and the answer key.

    Draws from the same generator as Stage 1, after it, in a fixed order, so Stage 1 files
    are unchanged (except authorizations.csv, where the late-authorization trap moves some
    authorized_at dates). Returns the canonical tables; only the raw files, the AP receipt log,
    the updated authorizations, and the labels are written.
    """
    rng = rng if rng is not None else np.random.default_rng(cfg["seed"])
    data_dir = Path(data_dir)

    invs, ctx = invoices.build_originals(tables, cfg, rng)
    traps.select_followups(invs, ctx, cfg, rng)
    auths = traps.apply_late_authorization(invs, ctx, tables["authorizations"], cfg, rng)
    traps.apply_bol_noise(invs, tables["shipments"]["bol"], cfg, rng)
    inject.inject_errors(invs, ctx, tables, cfg, rng)
    traps.apply_rounding_noise(invs, cfg, rng)
    traps.add_unknown_charges(invs, cfg, rng)
    traps.build_rebills(invs, ctx, cfg, rng)
    traps.build_balance_dues(invs, ctx, cfg, rng)
    inject.build_duplicates(invs, ctx, cfg, rng)
    inject.build_phantoms(invs, tables, cfg, rng)
    invoices.assign_ids(invs, cfg, rng)

    labels = ground_truth.build_labels(invs)
    receipt_log = invoices.invoice_frame(invs)[["carrier_id", "control_id", "received_date"]]
    receipt_log = receipt_log.sort_values(["received_date", "carrier_id", "control_id"]).reset_index(drop=True)
    files = render.render_invoices(invs, cfg, rng)

    write_csv(auths, data_dir / "reference" / "authorizations.csv")
    write_csv(receipt_log, data_dir / "reference" / "ap_receipt_log.csv")
    render.write_raw_files(files, data_dir)
    truth_dir = data_dir / "ground_truth"
    if truth_dir.exists():
        shutil.rmtree(truth_dir)
    truth_dir.mkdir(parents=True)
    write_csv(labels, truth_dir / "labels.csv")
    return {"authorizations": auths, "ap_receipt_log": receipt_log, "labels": labels,
            "invoices": invoices.invoice_frame(invs), "invoice_lines": invoices.line_frame(invs),
            "raw_files": files}


def generate_all(cfg, data_dir=REPO_ROOT / "data"):
    """Stage 1 then Stage 2 from one seeded generator. Returns all tables."""
    rng = np.random.default_rng(cfg["seed"])
    tables = generate_reference(cfg, data_dir, rng)
    tables.update(generate_invoices(cfg, tables, data_dir, rng))
    return tables
